SELECT * 
FROM Client cl
INNER JOIN Seller s
ON c.USERID = s.USERID
INNER JOIN Copy c
ON s.SELLERID = c.SELLERID
INNER JOIN Book b
ON c.BOOKID = b.BOOKID
WHERE b.TITLE LIKE '?'
OR 
b.AUTHOR LIKE '?'
OR
c.CLIENTNAME LIKE '?'
